# Generated by Django 5.2.4 on 2025-07-21 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('deskripsi', models.TextField()),
                ('kategori', models.CharField(blank=True, choices=[('sikap', 'Sikap'), ('pengetahuan', 'Pengetahuan'), ('keterampilan', 'Keterampilan')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Matakuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('sks', models.PositiveIntegerField()),
                ('semester', models.PositiveIntegerField()),
                ('pelaksanaan', models.IntegerField(choices=[(1, 'Teori'), (2, 'Praktek'), (3, 'Seminar/Simulasi'), (4, 'Kuliah Lapangan'), (5, 'Tugas Akhir')], default=1)),
                ('kelompokmk', models.IntegerField(choices=[(1, 'MKWK'), (2, 'Penciri UPGRIS'), (3, 'Wajib'), (4, 'Pilihan'), (5, 'Wajib Peminatan'), (6, 'Pilihan Peminatan'), (7, 'Tugas Akhir')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CPMK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20)),
                ('deskripsi', models.TextField()),
                ('cpl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpmks', to='kurikulum.cpl')),
                ('matakuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpmks', to='kurikulum.matakuliah')),
            ],
            options={
                'unique_together': {('kode', 'matakuliah')},
            },
        ),
        migrations.CreateModel(
            name='MatakuliahCPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.cpl')),
                ('matakuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.matakuliah')),
            ],
            options={
                'unique_together': {('matakuliah', 'cpl')},
            },
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='cpls',
            field=models.ManyToManyField(related_name='matakuliahs', through='kurikulum.MatakuliahCPL', to='kurikulum.cpl'),
        ),
        migrations.CreateModel(
            name='SubCPMK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('deskripsi', models.TextField()),
                ('durasi', models.PositiveIntegerField(blank=True, default=5)),
                ('bentuk', models.TextField(choices=[('teori', 'Perkuliahan Tatap Muka'), ('seminar', 'Presentasi/Seminar'), ('praktek', 'Praktikum/Laboratorium'), ('lapangan', 'Kuliah Lapangan/Industri')], default='teori', max_length=20)),
                ('indikator', models.TextField(blank=True, default='Mampu memahami....')),
                ('cpmk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcpmks', to='kurikulum.cpmk')),
            ],
            options={
                'unique_together': {('kode', 'cpmk')},
            },
        ),
    ]
