# Generated by Django 5.2.4 on 2025-07-19 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('deskripsi', models.TextField()),
                ('kategori', models.CharField(choices=[('sikap', 'Sikap'), ('pengetahuan', 'Pengetahuan'), ('keterampilan', 'Keterampilan')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Matakuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('sks', models.PositiveIntegerField()),
                ('semester', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MatakuliahCPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.cpl')),
                ('matakuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurikulum.matakuliah')),
            ],
            options={
                'unique_together': {('matakuliah', 'cpl')},
            },
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='cpls',
            field=models.ManyToManyField(related_name='matakuliahs', through='kurikulum.MatakuliahCPL', to='kurikulum.cpl'),
        ),
        migrations.CreateModel(
            name='CPMK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20)),
                ('deskripsi', models.TextField()),
                ('cpl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpmks', to='kurikulum.cpl')),
                ('matakuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpmks', to='kurikulum.matakuliah')),
            ],
            options={
                'unique_together': {('kode', 'matakuliah')},
            },
        ),
    ]
