# Generated by Django 5.2.4 on 2025-07-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCPMK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('deskripsi', models.TextField()),
                ('cpmk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcpmks', to='kurikulum.cpmk')),
            ],
        ),
    ]
