# Generated by Django 5.2.4 on 2025-07-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0002_subcpmk'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcpmk',
            name='bentuk',
            field=models.TextField(choices=[('teori', 'Perkuliahan Tatap Muka'), ('seminar', 'Presentasi/Seminar'), ('praktek', 'Praktikum/Laboratorium'), ('lapangan', 'Kuliah Lapangan/Industri')], default='teori', max_length=20),
        ),
        migrations.AddField(
            model_name='subcpmk',
            name='durasi',
            field=models.PositiveIntegerField(blank=True, default=5),
        ),
        migrations.AddField(
            model_name='subcpmk',
            name='indikator',
            field=models.TextField(blank=True, default='Mampu memahami....'),
        ),
        migrations.AlterUniqueTogether(
            name='subcpmk',
            unique_together={('kode', 'cpmk')},
        ),
    ]
