# Generated by Django 5.2.4 on 2025-07-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0003_subcpmk_bentuk_subcpmk_durasi_subcpmk_indikator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpl',
            name='kategori',
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='basicscience',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='kelompokmk',
            field=models.IntegerField(choices=[(None, 'Pilih Jenis Mata Kuliah'), (1, 'Mata Kuliah Wajib Kurikulum (MKWK)'), (2, 'Mata Kuliah Penciri Universitas'), (3, 'Mata Kuliah Wajib Prodi'), (4, 'Mata Kuliah Pilihan Prodi'), (5, 'Mata Kuliah Wajib Peminatan Prodi'), (6, 'Mata Kuliah Pilihan Peminatan Prodi'), (7, 'Mata Kuliah Tugas Akhir')], default=3),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='kkni',
            field=models.CharField(default='6', max_length=10),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='kodeprodi',
            field=models.IntegerField(default=66),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='pelaksanaan',
            field=models.IntegerField(choices=[(None, '-- Pilih Jenis Pelaksanaan --'), (1, 'Teori'), (2, 'Praktek'), (3, 'Seminar/Simulasi'), (4, 'Kuliah Lapangan'), (5, 'Tugas Akhir')], default=1, verbose_name='Metode Pelaksanaan'),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='tahunkurikulum',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='kode',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='semester',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='sks',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
