# Generated by Django 5.2.4 on 2025-07-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0004_remove_cpl_kategori_matakuliah_basicscience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpl',
            name='aspek',
            field=models.CharField(default='aspek', max_length=50),
        ),
        migrations.AddField(
            model_name='cpl',
            name='kkni',
            field=models.CharField(default='KK', max_length=20),
        ),
        migrations.AddField(
            model_name='cpl',
            name='sumber',
            field=models.CharField(default='Asosiasi', max_length=50),
        ),
        migrations.AddField(
            model_name='cpl',
            name='taksonomi',
            field=models.CharField(default='A5', max_length=50),
        ),
    ]
