# Generated by Django 5.2.4 on 2025-07-26 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0005_cpl_aspek_cpl_kkni_cpl_sumber_cpl_taksonomi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpl',
            old_name='kkni',
            new_name='kategori',
        ),
    ]
