# Generated by Django 5.2.4 on 2025-07-27 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0006_rename_kkni_cpl_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcpmk',
            name='bobot',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='subcpmk',
            name='cpmk',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcpmks', to='kurikulum.cpmk'),
        ),
    ]
