# Generated by Django 5.2.4 on 2025-07-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurikulum', '0007_subcpmk_bobot_alter_subcpmk_cpmk'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcpmk',
            name='jenistugas',
            field=models.CharField(blank=True, default='Tugas Latihan Soal', max_length=40),
        ),
    ]
